import { useEffect, useRef, useState } from 'react';
import { decode } from './protocol';
import { decodeSavedTeam } from './saved-team-protocol';
import { decodePreparedMatch } from './prepared-match-protocol';
import type { MatchRole, PreparedMatchDocument, PreparedMatchResponse } from './prepared-match-protocol';

type Team = { teamId: string; documentVersion: number; catalogVersion: string };
type Pending = { request: Record<string, unknown>; label: string; subject: 'home' | 'away' | null };
const url = 'ws://127.0.0.1:22227/browser/v1'; const retryKey = 'ffb.prepared-match.pending.v1'; const matchKey = 'ffb.prepared-match.id.v1';
function restoredPending(): Pending | null { try { const value = JSON.parse(sessionStorage.getItem(retryKey) ?? 'null'); if (!value || typeof value !== 'object' || typeof value.label !== 'string' || !('subject' in value) || (value.subject !== null && value.subject !== 'home' && value.subject !== 'away') || !value.request || typeof value.request !== 'object' || (value.request as Record<string, unknown>).type !== 'preparedMatch' || typeof (value.request as Record<string, unknown>).requestId !== 'string') return null; return value as Pending; } catch { return null; } }
export function MatchPanel() {
  const [token, setToken] = useState(''); const [status, setStatus] = useState('Disconnected'); const [teams, setTeams] = useState<Team[]>([]); const [teamId, setTeamId] = useState(''); const [opponent, setOpponent] = useState<MatchRole>('away'); const [matchId, setMatchId] = useState(() => sessionStorage.getItem(matchKey) ?? ''); const [document, setDocument] = useState<PreparedMatchDocument | null>(null); const [error, setError] = useState(''); const [pending, setPending] = useState<Pending | null>(restoredPending); const [assignedRole, setAssignedRole] = useState<MatchRole | null>(null);
  const socket = useRef<WebSocket | null>(null); const reconnectMatch = useRef(''); const pendingRef = useRef<Pending | null>(pending); const listRef = useRef(''); const subjectRef = useRef<'home' | 'away' | null>(null); pendingRef.current = pending;
  useEffect(() => () => socket.current?.close(), []); useEffect(() => { if (pending) sessionStorage.setItem(retryKey, JSON.stringify(pending)); else sessionStorage.removeItem(retryKey); }, [pending]); useEffect(() => { if (matchId) sessionStorage.setItem(matchKey, matchId); }, [matchId]);
  function send(request: Record<string, unknown>, label: string, retry = false) { if (socket.current?.readyState !== WebSocket.OPEN || (pendingRef.current && !retry)) return; if (!subjectRef.current) { setError('Wait for authenticated local identity before sending a match request.'); return; } if (retry && pendingRef.current?.subject !== subjectRef.current) { setError('This retained request belongs to a different local credential. Reconnect with the original credential.'); return; } if (!retry) { const next = { request, label, subject: subjectRef.current }; try { sessionStorage.setItem(retryKey, JSON.stringify(next)); } catch { setError('The request was not sent because retry storage is unavailable.'); return; } pendingRef.current = next; setPending(next); } socket.current.send(JSON.stringify(request)); }
  function accept(response: PreparedMatchResponse) { if (pendingRef.current?.request.requestId !== response.requestId) return; setAssignedRole(response.callerRole); if (response.document) { setDocument(response.document); setMatchId(response.document.matchId); reconnectMatch.current = response.document.matchId; } if (response.code === 'MATCH_OUTCOME_UNKNOWN') { if (response.recoveryMatchId) { setMatchId(response.recoveryMatchId); reconnectMatch.current = response.recoveryMatchId; } setError('The server may have committed this request but the acknowledgement was lost. The exact request is locked for reconciliation after reconnect.'); return; } try { sessionStorage.removeItem(retryKey); } catch { /* terminal response is still authoritative */ } pendingRef.current = null; setPending(null); setError(response.code === 'ACCEPTED' ? '' : `${response.code}: ${errorText(response.code)}`); }
  function load(id = matchId) { if (!id || socket.current?.readyState !== WebSocket.OPEN) return; send({ version: 1, type: 'preparedMatch', requestId: crypto.randomUUID(), operation: 'load', matchId: id }, 'load'); }
  function connect() { if (socket.current) return; const ws = new WebSocket(url); socket.current = ws; setStatus('Connecting'); let listId = ''; const current = () => socket.current === ws;
    ws.onopen = () => { if (!current()) return; const requestId = crypto.randomUUID(); ws.send(JSON.stringify({ version: 1, type: 'join', requestId, token })); setToken(''); };
    ws.onmessage = event => { if (!current()) return; try { const raw = JSON.parse(event.data) as { type?: string }; if (raw.type === 'preparedMatch') { accept(decodePreparedMatch(event.data)); return; } if (raw.type === 'savedTeam') { const saved = decodeSavedTeam(event.data); if (saved.requestId === listRef.current) { setTeams(saved.teams); setTeamId(value => saved.teams.some(team => team.teamId === value) ? value : saved.teams[0]?.teamId || ''); setStatus('Connected'); const recovery = restoredPending(); if (recovery) send(recovery.request, recovery.label, true); else if (reconnectMatch.current || sessionStorage.getItem(matchKey)) load(reconnectMatch.current || sessionStorage.getItem(matchKey)!); } return; } const result = decode(event.data); if (result.type === 'snapshot') { subjectRef.current = result.actor === 'home' || result.actor === 'away' ? result.actor : null; return; } if (result.type === 'result' && result.status === 'accepted') { listId = crypto.randomUUID(); listRef.current = listId; ws.send(JSON.stringify({ version: 1, type: 'savedTeam', requestId: listId, operation: 'list' })); } else if (result.type === 'result' && result.status === 'rejected') { setStatus(`Authentication failed: ${result.code}`); ws.close(); } } catch { setError('Invalid server response. Reconnect to reload the authoritative match.'); ws.close(); } };
    ws.onerror = () => current() && setStatus('Connection failed. Check the local server.'); ws.onclose = () => { if (!current()) return; socket.current = null; setStatus('Disconnected. Re-enter a local credential to reconnect.'); if (restoredPending()) setError('Connection closed before the result. The exact request is preserved and will reconcile after reconnect.'); };
  }
  function create() { const team = teams.find(item => item.teamId === teamId); if (team) send({ version: 1, type: 'preparedMatch', requestId: crypto.randomUUID(), operation: 'create', teamId: team.teamId, expectedDocumentVersion: team.documentVersion, intendedOpponent: opponent }, 'create'); }
  function join() { const team = teams.find(item => item.teamId === teamId); if (team && document) send({ version: 1, type: 'preparedMatch', requestId: crypto.randomUUID(), operation: 'join', matchId: document.matchId, expectedRevision: document.documentVersion, teamId: team.teamId, expectedDocumentVersion: team.documentVersion }, 'join'); }
  return <main className="team-builder match-panel"><nav><a href="/">Board scenarios</a> · <a href="/teams">Team builder</a> · <a href="/matches">Match preparation</a></nav><h1>Prepare a saved-team match</h1><p>Roles belong to this match. Your local credential does not choose home or away; the server assigns membership and checks the invitation.</p><form onSubmit={event => { event.preventDefault(); connect(); }}><label>Local credential <input aria-label="Local credential" type="password" value={token} onChange={event => setToken(event.target.value)} autoComplete="off" required /></label><button disabled={!!socket.current || !token}>Connect to saved teams</button></form><p role="status">{status}</p>{error && <p role="alert">{error}</p>}
    <p>Your assigned role: {assignedRole ?? 'not joined'}</p><section aria-label="Match controls"><label>Match ID <input aria-label="Match ID" value={matchId} onChange={event => setMatchId(event.target.value)} /></label><button type="button" className="secondary" onClick={() => load()} disabled={!!pending || status !== 'Connected' || !matchId}>Reload authoritative match</button>{teams.length > 0 && <><h2>Owned saved team</h2><label>Saved team <select aria-label="Saved team" value={teamId} onChange={event => setTeamId(event.target.value)}>{teams.map(team => <option key={team.teamId} value={team.teamId}>{team.teamId} · saved v{team.documentVersion} · {team.catalogVersion}</option>)}</select></label><button type="button" className="secondary" onClick={() => { const requestId = crypto.randomUUID(); listRef.current = requestId; socket.current?.send(JSON.stringify({ version: 1, type: 'savedTeam', requestId, operation: 'list' })); }} disabled={status !== 'Connected'}>Refresh saved teams</button>{!document && <><label>Invite intended opponent <select aria-label="Invite intended opponent" value={opponent} onChange={event => setOpponent(event.target.value as MatchRole)}><option value="away">Away local participant</option><option value="home">Home local participant</option></select></label><button type="button" onClick={create} disabled={!!pending || status !== 'Connected'}>Create match and freeze team</button></>}{document?.lifecycle === 'WAITING_FOR_OPPONENT' && <button type="button" onClick={join} disabled={!!pending || status !== 'Connected'}>Join vacant role with saved team</button>}</>}</section>
    {pending && <section><p role="status">Waiting for {pending.label} result…</p><button type="button" className="secondary" onClick={() => send(pending.request, pending.label, true)} disabled={status !== 'Connected'}>Retry exact request</button><p className="caption">New match mutations stay locked until this exact request is accepted or rejected.</p></section>}{document && <MatchDocument document={document} />}</main>;
}
function errorText(code: string) { return ({ AUTHORIZATION: 'You are not a match participant.', AUTHENTICATION_REQUIRED: 'Reconnect with a local credential.', NOT_FOUND: 'The authorized match or owned saved team was not found.', INVITATION_REQUIRED: 'This vacant role is reserved for the intended opponent.', STALE_REVISION: 'The match changed; reload before trying again.', STALE_TEAM_REVISION: 'The saved team changed; refresh saved teams before trying again.', INCOMPATIBLE_TEAM: 'The selected team is incompatible with this match.', CONFLICT: 'Another request already changed this match.', SEAT_OCCUPIED: 'The role has already been taken.', VALIDATION_FAILED: 'The selected saved team is no longer valid.', MIGRATION_REQUIRED: 'This saved team requires migration and cannot enter this match.', VERSION_UNAVAILABLE: 'The required catalog or preset is unavailable.', UNSUPPORTED_VERSION: 'This match document version is unsupported.', INVALID_REQUEST: 'The request was invalid.', SNAPSHOT_UNSUPPORTED: 'This frozen match cannot be interpreted by this server.', PERSISTENCE_FAILED: 'The save was rolled back; no match change was made.', REQUEST_ID_REUSED: 'That retry identifier was used with different request data.' } as Record<string, string>)[code] ?? 'The request was rejected; no local selection was discarded.'; }
function MatchDocument({ document }: { document: PreparedMatchDocument }) { const render = (member: PreparedMatchDocument['home'] | null) => member ? <li><strong>{member.role}</strong> · saved team {member.sourceTeamId} v{member.sourceDocumentVersion} · {member.ruleset}/{member.catalogVersion}/{member.rosterId}/{member.presetId} v{member.presetVersion} · validation {member.validation.valid ? 'accepted' : 'invalid'} · frozen players {member.roster.players.length}</li> : <li>away · waiting for intended opponent</li>; return <section aria-label="Authoritative prepared match"><h2>Authoritative prepared match</h2><p>Match {document.matchId} · revision {document.documentVersion} · {document.lifecycle.replaceAll('_', ' ').toLowerCase()} · invitation for {document.invitation.intendedOpponent}.</p><ul>{render(document.home)}{render(document.away)}</ul>{document.lifecycle === 'AWAITING_SETUP' && <p>Both accepted roster snapshots are frozen. Setup and gameplay are not part of this route.</p>}</section>; }
