import { useEffect, useRef, useState } from 'react';
import { decode } from './protocol.ts';
import { decodeMatchResult } from './result-protocol.ts';
import type { MatchResultCode, MatchResultMetadata, ReplayEvent } from './result-protocol.ts';

const endpoint = 'ws://127.0.0.1:22227/browser/v1';
const errorText = (code: MatchResultCode) => ({ NOT_FOUND: 'This completed match is not available to the authenticated participant.', NOT_COMPLETED: 'This match has not reached full time.', REPLAY_UNSUPPORTED: 'The saved replay cannot be interpreted by this browser.', PERSISTENCE_FAILED: 'The result could not be read from storage. Try again.', INVALID_REQUEST: 'The result request was invalid.', AUTHENTICATION_REQUIRED: 'Reconnect with a local credential.', SNAPSHOT_UNSUPPORTED: 'This saved result uses an unsupported snapshot.' } as Partial<Record<MatchResultCode, string>>)[code] ?? 'The result request was rejected.';
export function ResultPanel() {
  const [token, setToken] = useState(''); const [matchId, setMatchId] = useState(() => new URLSearchParams(location.search).get('matchId') ?? ''); const [status, setStatus] = useState('Disconnected'); const [error, setError] = useState(''); const [metadata, setMetadata] = useState<MatchResultMetadata | null>(null); const [event, setEvent] = useState<ReplayEvent | null>(null); const [index, setIndex] = useState<number | null>(null); const [pending, setPending] = useState(false);
  const socket = useRef<WebSocket | null>(null); const loadId = useRef(''); const replayId = useRef(''); const replayIndex = useRef<number | null>(null); const selectedMatch = useRef(matchId); const subject = useRef('');
  useEffect(() => () => socket.current?.close(), []);
  function request(operation: 'load' | 'replay', eventIndex?: number) { const ws = socket.current; if (!ws || ws.readyState !== WebSocket.OPEN || !selectedMatch.current || !subject.current || pending) return; const requestId = crypto.randomUUID(); if (operation === 'load') { loadId.current = requestId; replayId.current = ''; replayIndex.current = null; } else { replayId.current = requestId; replayIndex.current = eventIndex ?? null; } setPending(true); ws.send(JSON.stringify({ version: 1, type: 'matchResult', operation, requestId, matchId: selectedMatch.current, ...(operation === 'replay' ? { index: eventIndex } : {}) })); }
  function connect() { if (socket.current) return; selectedMatch.current = matchId; const ws = new WebSocket(endpoint); socket.current = ws; subject.current = ''; loadId.current = ''; replayId.current = ''; replayIndex.current = null; setPending(false); setStatus('Connecting'); setError(''); setMetadata(null); setEvent(null); setIndex(null); const current = () => socket.current === ws;
    ws.onopen = () => { if (current()) ws.send(JSON.stringify({ version: 1, type: 'join', requestId: crypto.randomUUID(), token })); };
    ws.onmessage = message => { if (!current()) return; try { const raw = JSON.parse(message.data) as { type?: string }; if (raw.type === 'matchResult') { const reply = decodeMatchResult(message.data); const isLoad = reply.requestId === loadId.current; const isReplay = reply.requestId === replayId.current; if (!isLoad && !isReplay) return; if (reply.result && reply.result.matchId !== selectedMatch.current) throw Error('Response belongs to another match'); setPending(false); if (reply.code !== 'ACCEPTED') { setError(`${reply.code}: ${errorText(reply.code)}`); return; } if (!reply.result || reply.result.matchId !== selectedMatch.current) return; setMetadata(reply.result); if (isReplay && reply.event && replayIndex.current !== null) { setEvent(reply.event); setIndex(replayIndex.current); } else if (isLoad) { setEvent(null); setIndex(null); } setError(''); return; } const reply = decode(message.data); if (reply.type === 'snapshot') { subject.current = reply.actor; setStatus('Connected'); setToken(''); request('load'); } else if (reply.type === 'result' && reply.status === 'rejected') { setError(`Authentication failed: ${reply.code}`); ws.close(); } } catch { setPending(false); setError('Invalid server response. Reconnect to reload the authoritative result.'); ws.close(); } };
    ws.onclose = () => { if (current()) { socket.current = null; setPending(false); setStatus('Disconnected'); } }; ws.onerror = () => current() && setError('Connection failed. Check the local server.'); }
  function replay(next: number) { if (!metadata || next < 0 || next >= metadata.eventCount) return; request('replay', next); }
  const ready = status === 'Connected' && !pending;
  return <main className="team-builder result-panel"><nav><a href="/matches">Match preparation</a> · <a href={`/setup?matchId=${encodeURIComponent(matchId)}`}>Match setup</a> · <a href="/teams">Team builder</a></nav><h1>Match result and replay</h1><p>Final score and recorded match history. Replay shows one recorded state at a time.</p><form onSubmit={item => { item.preventDefault(); connect(); }}><label>Local credential <input aria-label="Local credential" type="password" value={token} onChange={item => setToken(item.target.value)} autoComplete="off" required /></label><label>Match ID <input aria-label="Match ID" value={matchId} disabled={!!socket.current} onChange={item => setMatchId(item.target.value)} required /></label><button disabled={!!socket.current || !token || !matchId}>Load completed match</button></form><p role="status">{status}</p>{pending && <p role="status">Loading the saved result or replay event?</p>}{status === 'Disconnected' && <p>Re-enter your local credential to reload the saved result. Completed results survive server restart; an unfinished match cannot recover its engine after restart.</p>}<button type="button" className="secondary" onClick={() => request('load')} disabled={!ready}>Reload result</button><button type="button" className="secondary" onClick={() => socket.current?.close()} disabled={!socket.current}>Disconnect</button>{error && <p role="alert">{error}</p>}{metadata && <section aria-label="Authoritative result"><h2>Final score</h2><p className="result-score"><strong>Home {metadata.homeScore}</strong><span>–</span><strong>Away {metadata.awayScore}</strong></p><p>Final revision {metadata.finalRevision} · {metadata.eventCount} recorded events · {metadata.ruleset}</p><div className="replay-controls"><button type="button" onClick={() => replay(0)} disabled={!ready || index === 0}>First</button><button type="button" onClick={() => replay((index ?? 0) - 1)} disabled={!ready || index === null || index <= 0}>Previous</button><button type="button" onClick={() => replay((index ?? -1) + 1)} disabled={!ready || index === null || index >= metadata.eventCount - 1}>Next</button><button type="button" onClick={() => replay(metadata.eventCount - 1)} disabled={!ready || index === metadata.eventCount - 1}>Last</button></div>{event ? <ReplayState event={event} index={index ?? 0} total={metadata.eventCount} /> : <p>Select a replay control to view the match history.</p>}</section>}</main>;
}
function ReplayState({ event, index, total }: { event: ReplayEvent; index: number; total: number }) { const state = event.state; return <section aria-label="Replay event"><h2>Event {index + 1} of {total}: {event.kind}</h2><p>Revision {event.revision} · half {state.half} · drive {state.drive} · turns home {state.homeTurn}, away {state.awayTurn} · weather {state.weather}</p><div className="result-grid" aria-label="Read-only replay pitch">{Array.from({ length: 15 }, (_, y) => Array.from({ length: 26 }, (_, x) => { const player = state.players.find(item => item.x === x && item.y === y); return <span key={`${x},${y}`} className={player?.role ?? ''} aria-label={`Square ${x}, ${y}${player ? ` ${player.role} ${player.name}` : ''}`}>{player ? `${player.role === 'home' ? 'H' : 'A'}${player.slot}` : '·'}{state.ball?.x === x && state.ball.y === y ? ' ●' : ''}</span>; }))}</div><p>Ball {state.ball ? `${state.ball.x}, ${state.ball.y}` : 'off pitch'} · rerolls home {state.homeRerolls}, away {state.awayRerolls}</p></section>; }
