import { useEffect, useRef, useState } from 'react';
import { decode } from './protocol';
import { decodeTeam, emptyDraft } from './team-protocol';
import type { Catalog, TeamDraft, Validation } from './team-protocol';
import { decodeSavedDocument, decodeSavedTeam, parseUniqueJson } from './saved-team-protocol';
import type { SavedDocument } from './saved-team-protocol';
import { applySavedTeamResponse, canEditSavedTeam } from './saved-team-ui-state';
import { TeamValidationView } from './team-validation-view';

type TeamMeta = { teamId: string; documentVersion: number; catalogVersion: string };
type SavedOperation = { operation: 'list' } | { operation: 'load'; teamId: string } | { operation: 'create'; draft: TeamDraft } | { operation: 'update'; teamId: string; expectedDocumentVersion: number; draft: TeamDraft } | { operation: 'import'; document: SavedDocument };
export function TeamPanel() {
  const [token, setToken] = useState(''); const [status, setStatus] = useState('Disconnected'); const [catalog, setCatalog] = useState<Catalog | null>(null); const [draft, setDraft] = useState<TeamDraft | null>(null); const [result, setResult] = useState<Validation | null>(null);
  const [saved, setSaved] = useState<SavedDocument | null>(null); const [versionStatus, setVersionStatus] = useState<string | null>(null); const [teams, setTeams] = useState<TeamMeta[]>([]); const [pending, setPending] = useState(false); const [dirty, setDirty] = useState(false); const [outcomeUnknown, setOutcomeUnknown] = useState(false); const [positionId, setPositionId] = useState('lineman'); const [importText, setImportText] = useState('');
  const socket = useRef<WebSocket | null>(null); const expected = useRef<string | null>(null);
  const stateRef = useRef({ saved, draft, versionStatus, dirty, teams, status, pending });
  stateRef.current = { saved, draft, versionStatus, dirty, teams, status, pending };
  useEffect(() => () => { socket.current?.close(); socket.current = null; }, []);
  const editable = canEditSavedTeam(catalog?.catalogVersion ?? null, { saved, draft, versionStatus }, pending);
  const update = (next: TeamDraft) => { setDraft(next); setResult(null); setDirty(true); };
  function savedRequest(request: SavedOperation) { if (stateRef.current.pending || socket.current?.readyState !== WebSocket.OPEN) return; const requestId = crypto.randomUUID(); expected.current = requestId; setPending(true); socket.current.send(JSON.stringify({ version: 1, type: 'savedTeam', requestId, ...request })); }
  function acceptSaved(message: ReturnType<typeof decodeSavedTeam>) { const current = stateRef.current; const next = applySavedTeamResponse(current, message); setSaved(next.saved); setDraft(next.draft); setVersionStatus(next.versionStatus); setDirty(next.dirty); setTeams(next.teams); setStatus(message.code === 'SAVE_OUTCOME_UNKNOWN' ? `Save outcome unknown. Refresh and load team ${message.document?.teamId ?? current.saved?.teamId ?? 'before retrying'} before retrying.` : next.status); if (message.code === 'SAVE_OUTCOME_UNKNOWN') setOutcomeUnknown(true); else if (message.code === 'OK' && message.document) setOutcomeUnknown(false); if (message.validation) { const validationCatalog = message.document?.catalogVersion ?? current.draft?.catalogVersion ?? catalog?.catalogVersion; if (validationCatalog) setResult({ ...message.validation, version: 1, type: 'teamValidation', requestId: message.requestId, catalogVersion: validationCatalog, ruleset: 'BB2025' }); } }
  function connect() {
    if (socket.current) return; const ws = new WebSocket('ws://127.0.0.1:22227/browser/v1'); socket.current = ws; setStatus('Connecting'); setCatalog(null); setPending(true); const joinId = crypto.randomUUID(); let catalogId: string | null = null; const current = () => socket.current === ws;
    ws.onopen = () => { if (current()) { ws.send(JSON.stringify({ version: 1, type: 'join', requestId: joinId, token })); setToken(''); } };
    ws.onmessage = event => { if (!current()) return; try { const raw = JSON.parse(event.data) as { type?: string; requestId?: string };
      if (raw.type === 'savedTeam') { const message = decodeSavedTeam(event.data); if (message.requestId === expected.current) { expected.current = null; setPending(false); acceptSaved(message); } return; }
      if (raw.type === 'catalog' || raw.type === 'teamValidation') { const message = decodeTeam(event.data); if (message.type === 'catalog' && message.requestId === catalogId) { setCatalog(message); setDraft(previous => previous ?? emptyDraft(message)); setStatus('Connected'); catalogId = null; const listId = crypto.randomUUID(); expected.current = listId; setPending(true); ws.send(JSON.stringify({ version: 1, type: 'savedTeam', requestId: listId, operation: 'list' })); } else if (message.type === 'teamValidation' && message.requestId === expected.current) { setResult(message); expected.current = null; setPending(false); setStatus('Connected'); } return; }
      const message = decode(event.data); if (message.type === 'result' && message.requestId === joinId && message.status === 'accepted') { catalogId = crypto.randomUUID(); ws.send(JSON.stringify({ version: 1, type: 'catalog', requestId: catalogId })); } else if (message.type === 'result' && message.status === 'rejected' && (message.requestId === joinId || message.requestId === catalogId || message.requestId === expected.current)) { setStatus(`Request rejected: ${message.code}`); setPending(false); expected.current = null; if (message.requestId === joinId) ws.close(); }
    } catch { setStatus('Invalid server response. Reconnect to reload.'); ws.close(); } };
    ws.onerror = () => { if (current()) setStatus('Connection failed. Check the local server.'); }; ws.onclose = () => { if (current()) { socket.current = null; expected.current = null; setPending(false); setCatalog(null); setStatus('Disconnected. Re-enter a local credential to reconnect.'); } };
  }
  function addPlayer() { if (!draft || !catalog || !editable || draft.players.length >= catalog.maxPlayers) return; const slot = Array.from({ length: catalog.maxPlayers }, (_, index) => index + 1).find(value => !draft.players.some(player => player.slot === value))!; update({ ...draft, players: [...draft.players, { id: crypto.randomUUID(), slot, positionId, skillIds: [] }] }); }
  function validate() { if (!draft || !editable || socket.current?.readyState !== WebSocket.OPEN) return; const requestId = crypto.randomUUID(); expected.current = requestId; setPending(true); setResult(null); socket.current.send(JSON.stringify({ version: 1, type: 'validateTeam', requestId, draft })); }
  function save() { if (!draft || !editable || outcomeUnknown) return; if (saved) savedRequest({ operation: 'update', teamId: saved.teamId, expectedDocumentVersion: saved.documentVersion, draft }); else savedRequest({ operation: 'create', draft }); }
  function newDraft() { if (!catalog || pending) return; setSaved(null); setVersionStatus('CURRENT'); setOutcomeUnknown(false); setDraft(emptyDraft(catalog)); setResult(null); setDirty(true); }
  function importDocument(value: string) { if (outcomeUnknown) return; try { if (new TextEncoder().encode(value).length > 16000) throw Error(); const document = decodeSavedDocument(parseUniqueJson(value)); const envelope = JSON.stringify({ version: 1, type: 'savedTeam', requestId: '12345678-1234-1234-1234-123456789abc', operation: 'import', document }); if (new TextEncoder().encode(envelope).length > 16384) throw Error(); savedRequest({ operation: 'import', document }); } catch { setStatus('Import must be unique-key JSON that fits the 16 KiB protocol limit.'); } }
  function download() { if (!saved) return; const url = URL.createObjectURL(new Blob([JSON.stringify(saved, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `ffb-team-${saved.teamId}.json`; link.click(); URL.revokeObjectURL(url); }
  return <main className="team-builder"><nav><a href="/">Board scenarios</a> · <a href="/teams">Team builder</a> · <a href="/matches">Match preparation</a></nav><h1>BB2025 starter team builder</h1><p>Saved teams stay local to this credential. Use Match preparation to freeze an accepted saved version for an invited opponent.</p><form onSubmit={event => { event.preventDefault(); connect(); }}><label>Local credential <input aria-label="Local credential" type="password" value={token} onChange={event => setToken(event.target.value)} autoComplete="off" /></label><button disabled={pending || !!socket.current || !token}>Connect to catalog</button></form><p role="status">{status}{dirty ? ' · unsaved edits' : saved ? ` · saved version ${saved.documentVersion}` : ''}</p>
    {saved && <p>Selected team {saved.teamId} · saved document v{saved.documentVersion} · {saved.catalogVersion}. JSON export contains this saved version; unsaved edits are excluded.</p>}{outcomeUnknown && <p role="alert">Save outcome unknown. Refresh the list and load the attempted team before retrying. Your edits are preserved.</p>}
    {catalog && draft && <><h2>{catalog.name} · {catalog.budget.toLocaleString('en-US')} gold</h2><p>{catalog.league} · {catalog.specialRule} · {catalog.minPlayers}–{catalog.maxPlayers} players · {catalog.skillPoints} skill points</p><p>Catalog {catalog.catalogVersion}. {catalog.unsupported.replace('and match creation', 'and full match play')}</p><div className="catalog-table"><table><caption>Supported positions (AG, PA and AV are target numbers)</caption><thead><tr>{['Position', 'Limit', 'Gold', 'MA', 'ST', 'AG', 'PA', 'AV', 'Base skills', 'Primary / Secondary'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{catalog.positions.map(position => <tr key={position.id}><th>{position.name}</th><td>{position.maximum}</td><td>{position.cost.toLocaleString('en-US')}</td><td>{position.ma}</td><td>{position.st}</td><td>{position.ag}+</td><td>{position.pa}+</td><td>{position.av}+</td><td>{position.baseSkills.map(skill => `${catalog.skills.find(option => option.id === skill.id)?.name ?? skill.id}${skill.id === 'loner' ? ` (${skill.value}+)` : ''}`).join(', ') || 'None'}</td><td>{position.primary} / {position.secondary}</td></tr>)}</tbody></table></div><p>A: Agility · D: Devious · G: General · P: Passing · S: Strength. Purchased skills are limited to the options below.</p><section aria-label="Saved teams"><h2>Saved teams</h2><button type="button" onClick={() => savedRequest({ operation: 'list' })} disabled={pending}>Refresh list</button><button type="button" onClick={newDraft} disabled={pending}>Create new draft</button>{teams.length ? <ul>{teams.map(team => <li key={team.teamId}><code>{team.teamId}</code> · v{team.documentVersion} · {team.catalogVersion} <button type="button" onClick={() => savedRequest({ operation: 'load', teamId: team.teamId })} disabled={pending}>Load</button></li>)}</ul> : <p>No saved teams listed.</p>}<button type="button" onClick={save} disabled={!editable || !dirty || outcomeUnknown}>{saved ? 'Save changes' : 'Create saved team'}</button><button type="button" onClick={download} disabled={!saved}>Download JSON export</button><label>Import saved-team JSON <textarea aria-label="Import saved-team JSON" value={importText} maxLength={16000} onChange={event => setImportText(event.target.value)} /></label><button type="button" onClick={() => importDocument(importText)} disabled={pending || !importText || outcomeUnknown}>Import JSON</button><label>Import JSON file <input aria-label="Import JSON file" type="file" disabled={pending || outcomeUnknown} accept="application/json,.json" onChange={event => { const file = event.target.files?.[0]; if (!file || file.size > 16000) { setStatus('Import file must be at most 16 KiB.'); return; } file.text().then(importDocument); }} /></label></section>
      {versionStatus && versionStatus !== 'CURRENT' && <p role="alert">This saved document uses a catalog that cannot be edited: {versionStatus}. Its original draft remains available for export.</p>}{!editable && draft && !versionStatus && <p role="alert">Editing is locked until the saved document uses the current catalog.</p>}<fieldset disabled={!editable}><legend>Compose draft</legend><label>Position <select aria-label="Position" value={positionId} onChange={event => setPositionId(event.target.value)}>{catalog.positions.map(position => <option key={position.id} value={position.id}>{position.name}</option>)}</select></label><button type="button" onClick={addPlayer} disabled={draft.players.length >= catalog.maxPlayers}>Add player</button><ol>{draft.players.map(player => <li key={player.id}><span>Slot {player.slot}: {catalog.positions.find(position => position.id === player.positionId)?.name ?? player.positionId}</span><label>Skill for slot {player.slot} <select aria-label={`Skill for slot ${player.slot}`} value={player.skillIds[0] ?? ''} onChange={event => update({ ...draft, players: draft.players.map(item => item.id === player.id ? { ...item, skillIds: event.target.value ? [event.target.value] : [] } : item) })}><option value="">No purchased skill</option>{catalog.skills.filter(skill => skill.selectable).map(skill => <option key={skill.id} value={skill.id}>{skill.name}{skill.elite ? ' (Elite)' : ''}</option>)}</select></label><button type="button" aria-label={`Remove slot ${player.slot}`} onClick={() => update({ ...draft, captainId: draft.captainId === player.id ? null : draft.captainId, players: draft.players.filter(item => item.id !== player.id) })}>Remove</button></li>)}</ol><label>Team Captain <select aria-label="Team Captain" value={draft.captainId ?? ''} onChange={event => update({ ...draft, captainId: event.target.value || null })}><option value="">No captain</option>{draft.players.map(player => <option key={player.id} value={player.id}>Slot {player.slot}</option>)}</select></label><p>An eligible captain receives Pro at no gold or skill-point cost. Big Guys are ineligible.</p>{catalog.resources.map(resource => <label className="team-resource" key={resource.id}>{resource.name} ({resource.cost.toLocaleString('en-US')} gold each, maximum {resource.maximum}) <input aria-label={resource.name} type="number" step="1" value={draft.resources[resource.id]} onChange={event => update({ ...draft, resources: { ...draft.resources, [resource.id]: event.target.valueAsNumber } })}/></label>)}<button type="button" onClick={validate}>Validate draft on server</button></fieldset>{pending && <p role="status">Waiting for server…</p>}<TeamValidationView result={result}/></>}
  </main>;
}
